### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by whippingdot** [programmeruser2/gOS#1]
Sorry for creating an issue here but you didn't respond in GitHub or on replit so I wanted to ask you here cause i saw you were active recently.

So do you want to continue staying in the ReplitCoders org? We are reviving it (me and LeviathanCoding now known as IroncladDev) and we got a few 18 people and I wanted to know if you wanted to stay.

Also, to keep the org alive we are probably going to do 3 projects every year using a poll to decide what project to do in what quarter of the year. I would like to have you stay cause you are very good at programming and could help us with the projects! Also, you don't have to be jobless 24 / 7 and help us, just a few commits here and there in projects would be enough. We do have 4 months for every project so you could also just help for a month in a project ur interested in and then stop helping. Its ur decision I have done my best to convince you to stay and I hope you do!

**Comment by programmeruser2** [comment]
maybe from time to time, yes

**Comment by whippingdot** [comment]
so u r staying right? Thanks
